Qwen/Qwen1.5-4B_1:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1
  
Qwen/Qwen1.5-4B_2:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.1
  
Qwen/Qwen1.5-4B_3:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 32
  lora_alpha: 64
  lora_dropout: 0.1

Qwen/Qwen1.5-4B_4:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.1
  
Qwen/Qwen1.5-4B_5:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 128
  lora_alpha: 256
  lora_dropout: 0.1
  
Qwen/Qwen1.5-4B_6:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 4
  lora_rank: 256
  lora_alpha: 512
  lora_dropout: 0.1
