Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 6
  lora_rank: 32
  lora_alpha: 64
  lora_dropout: 0.1

Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 5
  lora_rank: 32
  lora_alpha: 64
  lora_dropout: 0.1

Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 5
  lora_rank: 64
  lora_alpha: 128
  lora_dropout: 0.1
